### ISSUE TITLE
Unhandled exception. System.IO.IOException: I/O error occurred when run sos command in lldb in .net 6.0 image

### ISSUE THREAD

**Issue by oldzhu** [oldzhu/4dotnet#7]
Unhandled exception. System.IO.IOException: I/O error occurred when run sos command in lldb in the new build .net 6.0 image
~~~
Unhandled exception. System.IO.IOException: I/O error occurred.
   at Microsoft.Diagnostics.Runtime.Utilities.Reader.Read[T](UInt64& position) in /home/oldzhu/buildroot/output/build/clrmd-origin_master/src/Microsoft.Diagnostics.Runtime/src/Linux/ElfReader.cs:line 53
   at Microsoft.Diagnostics.Runtime.Utilities.ElfDynamicSection..ctor(Reader reader, Boolean is64Bit, UInt64 address, UInt64 size) in /home/oldzhu/buildroot/output/build/clrmd-origin_master/src/Microsoft.Diagnostics.Runtime/src/Linux/ElfDynamicSection.cs:line 18
   at Microsoft.Diagnostics.Runtime.Utilities.ElfFile.get_DynamicSection() in /home/oldzhu/buildroot/output/build/clrmd-origin_master/src/Microsoft.Diagnostics.Runtime/src/Linux/ElfFile.cs:line 96
   at Microsoft.Diagnostics.Runtime.Utilities.ElfFile.TryGetExportSymbol(String symbolName, UInt64& offset) in /home/oldzhu/buildroot/output/build/clrmd-origin_master/src/Microsoft.Diagnostics.Runtime/src/Linux/ElfFile.cs:line 76
   at Microsoft.Diagnostics.DebugServices.Implementation.Module.Microsoft.Diagnostics.DebugServices.IExportSymbols.TryGetSymbolAddress(String name, UInt64& address) in /home/oldzhu/buildroot/output/build/diagnostics-origin_main/src/Microsoft.Diagnostics.DebugServices.Implementation/Module.cs:line 197
   at Microsoft.Diagnostics.DebugServices.Implementation.RuntimeService.Microsoft.Diagnostics.Runtime.IExportReader.TryGetSymbolAddress(UInt64 baseAddress, String name, UInt64& offset) in /home/oldzhu/buildroot/output/build/diagnostics-origin_main/src/Microsoft.Diagnostics.DebugServices.Implementation/RuntimeService.cs:line 224
   at Microsoft.Diagnostics.Runtime.DataTarget.GetOrCreateClrVersions() in /home/oldzhu/buildroot/output/build/clrmd-origin_master/src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTarget.cs:line 182
   at Microsoft.Diagnostics.DebugServices.Implementation.RuntimeService.EnumerateRuntimes() in /home/oldzhu/buildroot/output/build/diagnostics-origin_main/src/Microsoft.Diagnostics.DebugServices.Implementation/RuntimeService.cs:line 72
   at Microsoft.Diagnostics.DebugServices.Implementation.ContextService.GetCurrentRuntime() in /home/oldzhu/buildroot/output/build/diagnostics-origin_main/src/Microsoft.Diagnostics.DebugServices.Implementation/ContextService.cs:line 152
   at Microsoft.Diagnostics.DebugServices.Implementation.ContextService.<>c__DisplayClass5_0.<.ctor>b__0() in /home/oldzhu/buildroot/output/build/diagnostics-origin_main/src/Microsoft.Diagnostics.DebugServices.Implementation/ContextService.cs:line 29
   at Microsoft.Diagnostics.DebugServices.Implementation.ServiceProvider.GetService(Type type) in /home/oldzhu/buildroot/output/build/diagnostics-origin_main/src/Microsoft.Diagnostics.DebugServices.Implementation/ServiceProvider.cs:line 108
   at Microsoft.Diagnostics.DebugServices.ServiceProviderExtensions.GetService[T](IServiceProvider serviceProvider) in /home/oldzhu/buildroot/output/build/diagnostics-origin_main/src/Microsoft.Diagnostics.DebugServices/ServiceProviderExtensions.cs:line 19
   at SOS.Extensions.HostServices.CreateTarget(IntPtr self) in /home/oldzhu/buildroot/output/build/diagnostics-origin_main/src/SOS/SOS.Extensions/HostServices.cs:line 264
   at SOS.Extensions.HostServices.UpdateTarget(IntPtr self, UInt32 processId) in /home/oldzhu/buildroot/output/build/diagnostics-origin_main/src/SOS/SOS.Extensions/HostServices.cs:line 281
Aborted
~~~

**Comment by oldzhu** [comment]
https://github.com/dotnet/runtime/issues/62702#

**Comment by oldzhu** [comment]
it is fixed by https://github.com/dotnet/runtime/pull/62170#, include the patch into the project, when building the dotnet runtime 6.0.0 or 6.0.1, it will prompt which file to patch, choose to only patch the file corhlpr.h contained in buildroot dotnet runtime build folder and it will fix the exception in the VM built.
